/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CharactersListing: typeof import('./src/components/CharactersListing.vue')['default']
    EditCharacter: typeof import('./src/components/EditCharacter.vue')['default']
    EditPerso: typeof import('./src/components/EditPerso.vue')['default']
    EditPerson: typeof import('./src/components/EditPerson.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
